name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-setuptools
        pip3 install -r requirements.txt

    - name: Render
      run: |
        mkdir $GITHUB_WORKSPACE/build
        python3 render.py -t $GITHUB_WORKSPACE/build
        echo $GITHUB_WORKSPACE/build
        ls -la $GITHUB_WORKSPACE/build

    - name: Compile LaTeX document
      uses: dante-ev/latex-action@master
      with:
        root_file: /github/workspace/build/resume.tex
        args: "-lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=/github/workspace/build"

    - name: Shrink and copy PDF document
      run: tools/shrinkpdf2 $GITHUB_WORKSPACE/build/resume.pdf output/cristobal-resume.pdf

    - name: Generate LibreOffice document
      uses: docker://pandoc/core:2.9
      with:
        args: "./build/resume.md --output=output/cristobal-resume.odt"

    - name: Generate Word document
      uses: docker://pandoc/core:2.9
      with:
        args: "./build/resume.md --output=output/cristobal-resume.docx"

    - name: Copy Hugo document
      run: cp $GITHUB_WORKSPACE/build/resume.hugo output/cv.md
